name: Release APWorld
on:
  push:
    tags:
      - '**'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet add package Newtonsoft.Json --version 12.0.1
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Medievil*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}